"""minus_tokena

Revision ID: 0ae50394f20d
Revises: 
Create Date: 2023-12-09 18:07:37.227321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae50394f20d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=52), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=True),
    sa.Column('user2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friends_id'), 'friends', ['id'], unique=False)
    op.create_index(op.f('ix_friends_user1_id'), 'friends', ['user1_id'], unique=False)
    op.create_index(op.f('ix_friends_user2_id'), 'friends', ['user2_id'], unique=False)
    op.create_table('roomsusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('invent', sa.String(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roomsusers_id'), 'roomsusers', ['id'], unique=False)
    op.create_index(op.f('ix_roomsusers_room_id'), 'roomsusers', ['room_id'], unique=False)
    op.create_index(op.f('ix_roomsusers_user_id'), 'roomsusers', ['user_id'], unique=False)
    op.create_table('waiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=True),
    sa.Column('user2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiters_id'), 'waiters', ['id'], unique=False)
    op.create_index(op.f('ix_waiters_user1_id'), 'waiters', ['user1_id'], unique=False)
    op.create_index(op.f('ix_waiters_user2_id'), 'waiters', ['user2_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waiters_user2_id'), table_name='waiters')
    op.drop_index(op.f('ix_waiters_user1_id'), table_name='waiters')
    op.drop_index(op.f('ix_waiters_id'), table_name='waiters')
    op.drop_table('waiters')
    op.drop_index(op.f('ix_roomsusers_user_id'), table_name='roomsusers')
    op.drop_index(op.f('ix_roomsusers_room_id'), table_name='roomsusers')
    op.drop_index(op.f('ix_roomsusers_id'), table_name='roomsusers')
    op.drop_table('roomsusers')
    op.drop_index(op.f('ix_friends_user2_id'), table_name='friends')
    op.drop_index(op.f('ix_friends_user1_id'), table_name='friends')
    op.drop_index(op.f('ix_friends_id'), table_name='friends')
    op.drop_table('friends')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
