"""friends_waiters

Revision ID: 21c0649aad8a
Revises: 817d4f8d5ea0
Create Date: 2023-12-06 00:34:56.667730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c0649aad8a'
down_revision: Union[str, None] = '817d4f8d5ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=True),
    sa.Column('user2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friends_id'), 'friends', ['id'], unique=False)
    op.create_index(op.f('ix_friends_user1_id'), 'friends', ['user1_id'], unique=False)
    op.create_index(op.f('ix_friends_user2_id'), 'friends', ['user2_id'], unique=False)
    op.create_table('waiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=True),
    sa.Column('user2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiters_id'), 'waiters', ['id'], unique=False)
    op.create_index(op.f('ix_waiters_user1_id'), 'waiters', ['user1_id'], unique=False)
    op.create_index(op.f('ix_waiters_user2_id'), 'waiters', ['user2_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waiters_user2_id'), table_name='waiters')
    op.drop_index(op.f('ix_waiters_user1_id'), table_name='waiters')
    op.drop_index(op.f('ix_waiters_id'), table_name='waiters')
    op.drop_table('waiters')
    op.drop_index(op.f('ix_friends_user2_id'), table_name='friends')
    op.drop_index(op.f('ix_friends_user1_id'), table_name='friends')
    op.drop_index(op.f('ix_friends_id'), table_name='friends')
    op.drop_table('friends')
    # ### end Alembic commands ###
