"""unique_name

Revision ID: 6f42a2a4a828
Revises: b326f0c522cd
Create Date: 2023-12-08 01:44:05.098630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f42a2a4a828'
down_revision: Union[str, None] = 'b326f0c522cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rooms', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    # ### end Alembic commands ###
