"""Init

Revision ID: bf9e9c50eeac
Revises: 
Create Date: 2023-12-05 01:48:54.764938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9e9c50eeac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=52), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_vk', sa.Integer(), nullable=True),
    sa.Column('token_vk', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_vk')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_id_vk'), 'users', ['id_vk'], unique=True)
    op.create_table('roomsusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('invent', sa.String(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roomsusers_id'), 'roomsusers', ['id'], unique=False)
    op.create_index(op.f('ix_roomsusers_room_id'), 'roomsusers', ['room_id'], unique=False)
    op.create_index(op.f('ix_roomsusers_user_id'), 'roomsusers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roomsusers_user_id'), table_name='roomsusers')
    op.drop_index(op.f('ix_roomsusers_room_id'), table_name='roomsusers')
    op.drop_index(op.f('ix_roomsusers_id'), table_name='roomsusers')
    op.drop_table('roomsusers')
    op.drop_index(op.f('ix_users_id_vk'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
